import type { Language } from '@/constants/i18n';
import type { GrowthRingId } from '@/constants/growth-rings';

type RingCopy = {
  title: string;
  zone: string;
  thought: string;
};

const RING_COPY: Record<Language, Record<GrowthRingId, RingCopy>> = {
  en: {
    1: {
      title: 'Survival',
      zone: 'Most accessible',
      thought: 'The main thing is to get through this moment.',
    },
    2: {
      title: 'Basic functioning',
      zone: 'Home and routine',
      thought: 'I can do at least something.',
    },
    3: {
      title: 'Returning to the world',
      zone: 'Outer world',
      thought: 'I feel anxious, but I can keep going.',
    },
    4: {
      title: 'Life, not struggle',
      zone: 'Expanding life',
      thought: 'Anxiety may appear, but it no longer runs my life.',
    },
  },
  ru: {
    1: {
      title: 'Выживание',
      zone: 'Самое доступное',
      thought: 'Главное — пережить этот момент.',
    },
    2: {
      title: 'Базовое функционирование',
      zone: 'Дом и рутина',
      thought: 'Я могу сделать хотя бы что-то.',
    },
    3: {
      title: 'Возвращение в мир',
      zone: 'Внешний мир',
      thought: 'Мне тревожно, но я могу идти дальше.',
    },
    4: {
      title: 'Жизнь, а не борьба',
      zone: 'Расширение жизни',
      thought: 'Тревога может появляться, но она больше не управляет моей жизнью.',
    },
  },
  es: {
    1: { title: 'Supervivencia', zone: 'Lo más accesible', thought: 'Lo principal es atravesar este momento.' },
    2: { title: 'Funcionamiento básico', zone: 'Hogar y rutina', thought: 'Puedo hacer al menos algo.' },
    3: { title: 'Volver al mundo', zone: 'Mundo exterior', thought: 'Tengo ansiedad, pero puedo seguir.' },
    4: { title: 'Vida, no lucha', zone: 'Ampliar la vida', thought: 'La ansiedad puede aparecer, pero ya no dirige mi vida.' },
  },
  fr: {
    1: { title: 'Survie', zone: 'Le plus accessible', thought: 'L’essentiel est de traverser ce moment.' },
    2: { title: 'Fonctionnement de base', zone: 'Maison et routine', thought: 'Je peux faire au moins quelque chose.' },
    3: { title: 'Retour au monde', zone: 'Monde extérieur', thought: 'Je suis anxieux·se, mais je peux avancer.' },
    4: { title: 'La vie, pas le combat', zone: 'Élargir la vie', thought: 'L’anxiété peut venir, mais elle ne dirige plus ma vie.' },
  },
  de: {
    1: { title: 'Überleben', zone: 'Am zugänglichsten', thought: 'Wichtig ist, diesen Moment zu überstehen.' },
    2: { title: 'Grundfunktion', zone: 'Zuhause und Routine', thought: 'Ich kann zumindest etwas tun.' },
    3: { title: 'Zurück in die Welt', zone: 'Außenwelt', thought: 'Ich bin unruhig, aber ich kann weitergehen.' },
    4: { title: 'Leben, nicht Kampf', zone: 'Leben erweitern', thought: 'Angst darf kommen, steuert aber nicht mehr mein Leben.' },
  },
  zh: {
    1: { title: '生存', zone: '最容易做到', thought: '重要的是撑过这一刻。' },
    2: { title: '基本运转', zone: '家与日常', thought: '我至少能做一点事。' },
    3: { title: '回到世界', zone: '外部世界', thought: '我焦虑，但我可以继续前行。' },
    4: { title: '生活，而不是对抗', zone: '拓展生活', thought: '焦虑可能出现，但不再主导我的生活。' },
  },
  pt: {
    1: { title: 'Sobrevivência', zone: 'O mais acessível', thought: 'O principal é atravessar este momento.' },
    2: { title: 'Funcionamento básico', zone: 'Casa e rotina', thought: 'Posso fazer pelo menos alguma coisa.' },
    3: { title: 'Voltar ao mundo', zone: 'Mundo externo', thought: 'Estou ansioso(a), mas posso seguir.' },
    4: { title: 'Vida, não luta', zone: 'Expandir a vida', thought: 'A ansiedade pode aparecer, mas não governa mais minha vida.' },
  },
  it: {
    1: { title: 'Sopravvivenza', zone: 'Il più accessibile', thought: 'L’importante è attraversare questo momento.' },
    2: { title: 'Funzionamento di base', zone: 'Casa e routine', thought: 'Posso fare almeno qualcosa.' },
    3: { title: 'Ritorno al mondo', zone: 'Mondo esterno', thought: 'Sono in ansia, ma posso andare avanti.' },
    4: { title: 'Vita, non lotta', zone: 'Ampliare la vita', thought: 'L’ansia può comparire, ma non governa più la mia vita.' },
  },
  ja: {
    1: { title: '生存', zone: 'いちばん取り組みやすい', thought: '大切なのは、この瞬間を乗り越えること。' },
    2: { title: '基本的な生活', zone: '家とルーティン', thought: '少なくとも何かはできる。' },
    3: { title: '世界へ戻る', zone: '外の世界', thought: '不安だけど、進める。' },
    4: { title: '闘いではなく人生', zone: '人生を広げる', thought: '不安は来ても、もう人生を支配しない。' },
  },
  ko: {
    1: { title: '생존', zone: '가장 쉽게 할 수 있는 것', thought: '중요한 건 이 순간을 견디는 것이다.' },
    2: { title: '기본 기능', zone: '집과 루틴', thought: '적어도 무언가는 할 수 있다.' },
    3: { title: '세상으로 돌아가기', zone: '바깥세상', thought: '불안하지만 앞으로 갈 수 있다.' },
    4: { title: '투쟁이 아닌 삶', zone: '삶을 넓히기', thought: '불안은 올 수 있지만 더 이상 삶을 지배하지 않는다.' },
  },
};

const ACTION_LABELS: Record<Language, Record<string, string>> = {
  en: {
    'take-meds': 'Take medication',
    eat: 'Eat',
    'drink-water': 'Drink water',
    'go-to-bed': 'Go to bed',
    'check-pulse': 'Check pulse or blood pressure',
    'message-someone': 'Message someone close',
    shower: 'Take a shower',
    cook: 'Cook a meal',
    'tidy-room': 'Tidy the room',
    'reply-message': 'Reply to a message',
    'diary-entry': 'Write in the diary',
    'short-walk': 'Take a short walk',
    'outing-near-home': 'Outing near home',
    'talk-close-only': 'Talk only with close ones',
    'work-from-home': 'Work from home',
    'trip-with-companion': 'Trip only with a companion',
    'home-workout': 'Home workout',
    'go-shopping': 'Go to the store',
    'meet-friend': 'Meet a friend',
    'public-transport': 'Take public transport',
    exercise: 'Exercise',
    'work-hours': 'Work for a few hours',
    'visit-cafe': 'Visit a cafe',
    travel: 'Travel',
    'learn-new': 'Learn something new',
    'plan-future': 'Plan the future',
    hobby: 'Do a hobby',
    'speak-public': 'Speak in public',
    'change-plans': 'Change plans spontaneously',
    'new-acquaintances': 'New acquaintances',
  },
  ru: {
    'take-meds': 'Принять лекарство',
    eat: 'Поесть',
    'drink-water': 'Пить воду',
    'go-to-bed': 'Лечь в кровать',
    'check-pulse': 'Проверить пульс или давление',
    'message-someone': 'Написать близкому человеку',
    shower: 'Принять душ',
    cook: 'Приготовить еду',
    'tidy-room': 'Убрать в комнате',
    'reply-message': 'Ответить на сообщение',
    'diary-entry': 'Сделать запись в дневнике',
    'short-walk': 'Выйти на короткую прогулку',
    'outing-near-home': 'Поход рядом с домом',
    'talk-close-only': 'Общение только с близкими',
    'work-from-home': 'Работа из дома',
    'trip-with-companion': 'Поездка только с сопровождением',
    'home-workout': 'Тренировка дома',
    'go-shopping': 'Сходить в магазин',
    'meet-friend': 'Встретиться с другом',
    'public-transport': 'Поехать на транспорте',
    exercise: 'Заняться спортом',
    'work-hours': 'Работать несколько часов',
    'visit-cafe': 'Посетить кафе',
    travel: 'Путешествовать',
    'learn-new': 'Учиться новому',
    'plan-future': 'Планировать будущее',
    hobby: 'Заниматься хобби',
    'speak-public': 'Выступать публично',
    'change-plans': 'Спонтанно менять планы',
    'new-acquaintances': 'Новые знакомства',
  },
  es: {
    'take-meds': 'Tomar el medicamento',
    eat: 'Comer',
    'drink-water': 'Beber agua',
    'go-to-bed': 'Acostarse',
    'check-pulse': 'Comprobar pulso o presión',
    'message-someone': 'Escribir a alguien cercano',
    shower: 'Ducharse',
    cook: 'Preparar comida',
    'tidy-room': 'Ordenar la habitación',
    'reply-message': 'Responder un mensaje',
    'diary-entry': 'Escribir en el diario',
    'short-walk': 'Salir a un paseo corto',
    'outing-near-home': 'Salida cerca de casa',
    'talk-close-only': 'Hablar solo con seres cercanos',
    'work-from-home': 'Trabajar desde casa',
    'trip-with-companion': 'Viaje solo con acompañamiento',
    'home-workout': 'Entrenar en casa',
    'go-shopping': 'Ir a la tienda',
    'meet-friend': 'Quedar con un amigo',
    'public-transport': 'Usar transporte público',
    exercise: 'Hacer deporte',
    'work-hours': 'Trabajar unas horas',
    'visit-cafe': 'Ir a un café',
    travel: 'Viajar',
    'learn-new': 'Aprender algo nuevo',
    'plan-future': 'Planificar el futuro',
    hobby: 'Practicar un hobby',
    'speak-public': 'Hablar en público',
    'change-plans': 'Cambiar planes de forma espontánea',
    'new-acquaintances': 'Nuevos conocidos',
  },
  fr: {
    'take-meds': 'Prendre le médicament',
    eat: 'Manger',
    'drink-water': 'Boire de l’eau',
    'go-to-bed': 'Se coucher',
    'check-pulse': 'Vérifier le pouls ou la tension',
    'message-someone': 'Écrire à un proche',
    shower: 'Prendre une douche',
    cook: 'Préparer un repas',
    'tidy-room': 'Ranger sa chambre',
    'reply-message': 'Répondre à un message',
    'diary-entry': 'Écrire dans le journal',
    'short-walk': 'Faire une courte promenade',
    'outing-near-home': 'Sortie près de chez soi',
    'talk-close-only': 'Parler seulement aux proches',
    'work-from-home': 'Travailler de chez soi',
    'trip-with-companion': 'Sortie seulement accompagné·e',
    'home-workout': 'S’entraîner à la maison',
    'go-shopping': 'Aller au magasin',
    'meet-friend': 'Voir un ami',
    'public-transport': 'Prendre les transports',
    exercise: 'Faire du sport',
    'work-hours': 'Travailler quelques heures',
    'visit-cafe': 'Aller au café',
    travel: 'Voyager',
    'learn-new': 'Apprendre quelque chose de nouveau',
    'plan-future': 'Planifier l’avenir',
    hobby: 'Pratiquer un hobby',
    'speak-public': 'Parler en public',
    'change-plans': 'Changer de plans spontanément',
    'new-acquaintances': 'Nouvelles rencontres',
  },
  de: {
    'take-meds': 'Medikament nehmen',
    eat: 'Essen',
    'drink-water': 'Wasser trinken',
    'go-to-bed': 'Ins Bett gehen',
    'check-pulse': 'Puls oder Blutdruck prüfen',
    'message-someone': 'Jemandem Nahen schreiben',
    shower: 'Duschen',
    cook: 'Essen kochen',
    'tidy-room': 'Zimmer aufräumen',
    'reply-message': 'Auf eine Nachricht antworten',
    'diary-entry': 'Im Tagebuch schreiben',
    'short-walk': 'Kurzen Spaziergang machen',
    'outing-near-home': 'Ausflug in der Nähe',
    'talk-close-only': 'Nur mit Nahestehenden sprechen',
    'work-from-home': 'Von zu Hause arbeiten',
    'trip-with-companion': 'Nur in Begleitung unterwegs',
    'home-workout': 'Training zu Hause',
    'go-shopping': 'Einkaufen gehen',
    'meet-friend': 'Einen Freund treffen',
    'public-transport': 'Öffentliche Verkehrsmittel nutzen',
    exercise: 'Sport treiben',
    'work-hours': 'Einige Stunden arbeiten',
    'visit-cafe': 'Ins Café gehen',
    travel: 'Reisen',
    'learn-new': 'Neues lernen',
    'plan-future': 'Zukunft planen',
    hobby: 'Hobby betreiben',
    'speak-public': 'Öffentlich sprechen',
    'change-plans': 'Pläne spontan ändern',
    'new-acquaintances': 'Neue Bekanntschaften',
  },
  zh: {
    'take-meds': '服药',
    eat: '吃饭',
    'drink-water': '喝水',
    'go-to-bed': '上床休息',
    'check-pulse': '测脉搏或血压',
    'message-someone': '给亲近的人发消息',
    shower: '洗澡',
    cook: '做饭',
    'tidy-room': '整理房间',
    'reply-message': '回复消息',
    'diary-entry': '写日记',
    'short-walk': '短短散步',
    'outing-near-home': '在家附近外出',
    'talk-close-only': '只与亲近的人交流',
    'work-from-home': '在家工作',
    'trip-with-companion': '仅在有人陪同下出行',
    'home-workout': '在家锻炼',
    'go-shopping': '去商店',
    'meet-friend': '见朋友',
    'public-transport': '乘坐公共交通',
    exercise: '运动',
    'work-hours': '工作几小时',
    'visit-cafe': '去咖啡馆',
    travel: '旅行',
    'learn-new': '学新东西',
    'plan-future': '规划未来',
    hobby: '做爱好',
    'speak-public': '公开发言',
    'change-plans': '临时改变计划',
    'new-acquaintances': '结识新朋友',
  },
  pt: {
    'take-meds': 'Tomar o medicamento',
    eat: 'Comer',
    'drink-water': 'Beber água',
    'go-to-bed': 'Deitar-se',
    'check-pulse': 'Verificar pulso ou pressão',
    'message-someone': 'Escrever para alguém próximo',
    shower: 'Tomar banho',
    cook: 'Preparar comida',
    'tidy-room': 'Arrumar o quarto',
    'reply-message': 'Responder a uma mensagem',
    'diary-entry': 'Escrever no diário',
    'short-walk': 'Fazer um passeio curto',
    'outing-near-home': 'Saída perto de casa',
    'talk-close-only': 'Conversar só com pessoas próximas',
    'work-from-home': 'Trabalhar de casa',
    'trip-with-companion': 'Saída só com acompanhante',
    'home-workout': 'Treinar em casa',
    'go-shopping': 'Ir ao mercado',
    'meet-friend': 'Encontrar um amigo',
    'public-transport': 'Usar transporte público',
    exercise: 'Praticar esporte',
    'work-hours': 'Trabalhar algumas horas',
    'visit-cafe': 'Ir a um café',
    travel: 'Viajar',
    'learn-new': 'Aprender algo novo',
    'plan-future': 'Planejar o futuro',
    hobby: 'Praticar um hobby',
    'speak-public': 'Falar em público',
    'change-plans': 'Mudar planos espontaneamente',
    'new-acquaintances': 'Novos conhecidos',
  },
  it: {
    'take-meds': 'Assumere il farmaco',
    eat: 'Mangiare',
    'drink-water': 'Bere acqua',
    'go-to-bed': 'Andare a letto',
    'check-pulse': 'Controllare polso o pressione',
    'message-someone': 'Scrivere a una persona cara',
    shower: 'Fare la doccia',
    cook: 'Preparare da mangiare',
    'tidy-room': 'Riordinare la stanza',
    'reply-message': 'Rispondere a un messaggio',
    'diary-entry': 'Scrivere nel diario',
    'short-walk': 'Fare una breve passeggiata',
    'outing-near-home': 'Uscita vicino a casa',
    'talk-close-only': 'Parlare solo con i cari',
    'work-from-home': 'Lavorare da casa',
    'trip-with-companion': 'Uscita solo accompagnati',
    'home-workout': 'Allenarsi a casa',
    'go-shopping': 'Andare al negozio',
    'meet-friend': 'Incontrare un amico',
    'public-transport': 'Prendere i mezzi',
    exercise: 'Fare sport',
    'work-hours': 'Lavorare alcune ore',
    'visit-cafe': 'Andare al bar',
    travel: 'Viaggiare',
    'learn-new': 'Imparare qualcosa di nuovo',
    'plan-future': 'Pianificare il futuro',
    hobby: 'Dedicarsi a un hobby',
    'speak-public': 'Parlare in pubblico',
    'change-plans': 'Cambiare piani spontaneamente',
    'new-acquaintances': 'Nuove conoscenze',
  },
  ja: {
    'take-meds': '薬を飲む',
    eat: '食べる',
    'drink-water': '水を飲む',
    'go-to-bed': 'ベッドに入る',
    'check-pulse': '脈や血圧を測る',
    'message-someone': '大切な人にメッセージする',
    shower: 'シャワーを浴びる',
    cook: '食事を作る',
    'tidy-room': '部屋を片づける',
    'reply-message': 'メッセージに返信する',
    'diary-entry': '日記を書く',
    'short-walk': '短い散歩に出る',
    'outing-near-home': '家の近くのお出かけ',
    'talk-close-only': '親しい人とのみ話す',
    'work-from-home': '在宅で働く',
    'trip-with-companion': '付き添いありでの外出',
    'home-workout': '自宅でトレーニング',
    'go-shopping': 'お店に行く',
    'meet-friend': '友達に会う',
    'public-transport': '公共交通を使う',
    exercise: '運動する',
    'work-hours': '数時間働く',
    'visit-cafe': 'カフェに行く',
    travel: '旅行する',
    'learn-new': '新しいことを学ぶ',
    'plan-future': '将来を計画する',
    hobby: '趣味をする',
    'speak-public': '人前で話す',
    'change-plans': '予定を思いつきで変える',
    'new-acquaintances': '新しい出会い',
  },
  ko: {
    'take-meds': '약 복용하기',
    eat: '먹기',
    'drink-water': '물 마시기',
    'go-to-bed': '침대에 눕기',
    'check-pulse': '맥박이나 혈압 확인하기',
    'message-someone': '가까운 사람에게 메시지 보내기',
    shower: '샤워하기',
    cook: '음식 준비하기',
    'tidy-room': '방 정리하기',
    'reply-message': '메시지 답장하기',
    'diary-entry': '일기 쓰기',
    'short-walk': '짧은 산책하기',
    'outing-near-home': '집 근처 외출',
    'talk-close-only': '가까운 사람과만 소통하기',
    'work-from-home': '재택 근무하기',
    'trip-with-companion': '동행과 함께만 이동하기',
    'home-workout': '집에서 운동하기',
    'go-shopping': '가게에 가기',
    'meet-friend': '친구 만나기',
    'public-transport': '대중교통 이용하기',
    exercise: '운동하기',
    'work-hours': '몇 시간 일하기',
    'visit-cafe': '카페 가기',
    travel: '여행하기',
    'learn-new': '새로운 것 배우기',
    'plan-future': '미래 계획하기',
    hobby: '취미 하기',
    'speak-public': '공개적으로 말하기',
    'change-plans': '즉흥적으로 계획 바꾸기',
    'new-acquaintances': '새로운 만남',
  },
};

const EMOTION_LABELS: Record<Language, Record<string, string>> = {
  en: {
    fear: 'Fear',
    anxiety: 'Anxiety',
    tension: 'Tension',
    vulnerability: 'Vulnerability',
    'need-safety': 'Need for safety',
    caution: 'Caution',
    fatigue: 'Fatigue',
    'small-relief': 'Slight relief',
    hope: 'Hope',
    interest: 'Interest',
    uncertainty: 'Uncertainty',
    excitement: 'Excitement',
    pride: 'Pride in myself',
    joy: 'Joy',
    curiosity: 'Curiosity',
    enthusiasm: 'Enthusiasm',
    freedom: 'Freedom',
    satisfaction: 'Satisfaction',
    confidence: 'Confidence',
    'fear-of-symptoms': 'Fear of symptoms',
    'constant-vigilance': 'Constant vigilance',
    'relief-after-home': 'Relief after returning home',
  },
  ru: {
    fear: 'Страх',
    anxiety: 'Тревога',
    tension: 'Напряжение',
    vulnerability: 'Уязвимость',
    'need-safety': 'Потребность в безопасности',
    caution: 'Осторожность',
    fatigue: 'Усталость',
    'small-relief': 'Небольшое облегчение',
    hope: 'Надежда',
    interest: 'Интерес',
    uncertainty: 'Неуверенность',
    excitement: 'Волнение',
    pride: 'Гордость за себя',
    joy: 'Радость',
    curiosity: 'Любопытство',
    enthusiasm: 'Воодушевление',
    freedom: 'Свобода',
    satisfaction: 'Удовлетворение',
    confidence: 'Уверенность',
    'fear-of-symptoms': 'Страх симптомов',
    'constant-vigilance': 'Постоянная настороженность',
    'relief-after-home': 'Облегчение после возвращения домой',
  },
  es: {
    fear: 'Miedo',
    anxiety: 'Ansiedad',
    tension: 'Tensión',
    vulnerability: 'Vulnerabilidad',
    'need-safety': 'Necesidad de seguridad',
    caution: 'Cautela',
    fatigue: 'Cansancio',
    'small-relief': 'Pequeño alivio',
    hope: 'Esperanza',
    interest: 'Interés',
    uncertainty: 'Inseguridad',
    excitement: 'Emoción',
    pride: 'Orgullo de mí',
    joy: 'Alegría',
    curiosity: 'Curiosidad',
    enthusiasm: 'Entusiasmo',
    freedom: 'Libertad',
    satisfaction: 'Satisfacción',
    confidence: 'Confianza',
    'fear-of-symptoms': 'Miedo a los síntomas',
    'constant-vigilance': 'Alerta constante',
    'relief-after-home': 'Alivio al volver a casa',
  },
  fr: {
    fear: 'Peur',
    anxiety: 'Anxiété',
    tension: 'Tension',
    vulnerability: 'Vulnérabilité',
    'need-safety': 'Besoin de sécurité',
    caution: 'Prudence',
    fatigue: 'Fatigue',
    'small-relief': 'Léger soulagement',
    hope: 'Espoir',
    interest: 'Intérêt',
    uncertainty: 'Incertitude',
    excitement: 'Émoi',
    pride: 'Fierté de soi',
    joy: 'Joie',
    curiosity: 'Curiosité',
    enthusiasm: 'Enthousiasme',
    freedom: 'Liberté',
    satisfaction: 'Satisfaction',
    confidence: 'Confiance',
    'fear-of-symptoms': 'Peur des symptômes',
    'constant-vigilance': 'Vigilance constante',
    'relief-after-home': 'Soulagement après le retour à la maison',
  },
  de: {
    fear: 'Angst',
    anxiety: 'Unruhe',
    tension: 'Anspannung',
    vulnerability: 'Verletzlichkeit',
    'need-safety': 'Bedürfnis nach Sicherheit',
    caution: 'Vorsicht',
    fatigue: 'Müdigkeit',
    'small-relief': 'Leichte Erleichterung',
    hope: 'Hoffnung',
    interest: 'Interesse',
    uncertainty: 'Unsicherheit',
    excitement: 'Aufregung',
    pride: 'Stolz auf mich',
    joy: 'Freude',
    curiosity: 'Neugier',
    enthusiasm: 'Begeisterung',
    freedom: 'Freiheit',
    satisfaction: 'Zufriedenheit',
    confidence: 'Zuversicht',
    'fear-of-symptoms': 'Angst vor Symptomen',
    'constant-vigilance': 'Ständige Wachsamkeit',
    'relief-after-home': 'Erleichterung nach der Heimkehr',
  },
  zh: {
    fear: '恐惧',
    anxiety: '焦虑',
    tension: '紧绷',
    vulnerability: '脆弱',
    'need-safety': '需要安全感',
    caution: '谨慎',
    fatigue: '疲劳',
    'small-relief': '轻微放松',
    hope: '希望',
    interest: '兴趣',
    uncertainty: '不确定',
    excitement: '激动',
    pride: '为自己骄傲',
    joy: '喜悦',
    curiosity: '好奇',
    enthusiasm: '振奋',
    freedom: '自由',
    satisfaction: '满足',
    confidence: '自信',
    'fear-of-symptoms': '害怕症状',
    'constant-vigilance': '持续警惕',
    'relief-after-home': '回家后的轻松感',
  },
  pt: {
    fear: 'Medo',
    anxiety: 'Ansiedade',
    tension: 'Tensão',
    vulnerability: 'Vulnerabilidade',
    'need-safety': 'Necessidade de segurança',
    caution: 'Cautela',
    fatigue: 'Cansaço',
    'small-relief': 'Pequeno alívio',
    hope: 'Esperança',
    interest: 'Interesse',
    uncertainty: 'Insegurança',
    excitement: 'Agitação',
    pride: 'Orgulho de si',
    joy: 'Alegria',
    curiosity: 'Curiosidade',
    enthusiasm: 'Entusiasmo',
    freedom: 'Liberdade',
    satisfaction: 'Satisfação',
    confidence: 'Confiança',
    'fear-of-symptoms': 'Medo dos sintomas',
    'constant-vigilance': 'Vigilância constante',
    'relief-after-home': 'Alívio ao voltar para casa',
  },
  it: {
    fear: 'Paura',
    anxiety: 'Ansia',
    tension: 'Tensione',
    vulnerability: 'Vulnerabilità',
    'need-safety': 'Bisogno di sicurezza',
    caution: 'Cautela',
    fatigue: 'Stanchezza',
    'small-relief': 'Piccolo sollievo',
    hope: 'Speranza',
    interest: 'Interesse',
    uncertainty: 'Insicurezza',
    excitement: 'Emozione',
    pride: 'Orgoglio di sé',
    joy: 'Gioia',
    curiosity: 'Curiosità',
    enthusiasm: 'Entusiasmo',
    freedom: 'Libertà',
    satisfaction: 'Soddisfazione',
    confidence: 'Fiducia in sé',
    'fear-of-symptoms': 'Paura dei sintomi',
    'constant-vigilance': 'Allerta costante',
    'relief-after-home': 'Sollievo dopo il rientro a casa',
  },
  ja: {
    fear: '恐れ',
    anxiety: '不安',
    tension: '緊張',
    vulnerability: '傷つきやすさ',
    'need-safety': '安全への欲求',
    caution: '慎重さ',
    fatigue: '疲労',
    'small-relief': '少しの安心',
    hope: '希望',
    interest: '興味',
    uncertainty: '迷い',
    excitement: 'ときめき',
    pride: '自分への誇り',
    joy: '喜び',
    curiosity: '好奇心',
    enthusiasm: '高揚',
    freedom: '自由',
    satisfaction: '満足',
    confidence: '自信',
    'fear-of-symptoms': '症状への恐れ',
    'constant-vigilance': '常に警戒している感じ',
    'relief-after-home': '帰宅後の安心',
  },
  ko: {
    fear: '두려움',
    anxiety: '불안',
    tension: '긴장',
    vulnerability: '취약함',
    'need-safety': '안전에 대한 욕구',
    caution: '조심스러움',
    fatigue: '피로',
    'small-relief': '약간의 안도',
    hope: '희망',
    interest: '흥미',
    uncertainty: '불확실함',
    excitement: '설렘',
    pride: '자신에 대한 자부심',
    joy: '기쁨',
    curiosity: '호기심',
    enthusiasm: '의욕',
    freedom: '자유',
    satisfaction: '만족',
    confidence: '자신감',
    'fear-of-symptoms': '증상에 대한 두려움',
    'constant-vigilance': '끊임없는 경계심',
    'relief-after-home': '집에 돌아온 후의 안도',
  },
};

export function getGrowthRingCopy(language: Language, ringId: GrowthRingId): RingCopy {
  return RING_COPY[language]?.[ringId] ?? RING_COPY.en[ringId];
}

export function getGrowthRingActionLabel(language: Language, actionId: string): string {
  return ACTION_LABELS[language]?.[actionId] ?? ACTION_LABELS.en[actionId] ?? actionId;
}

export function getGrowthRingEmotionLabel(language: Language, emotionId: string): string {
  return EMOTION_LABELS[language]?.[emotionId] ?? EMOTION_LABELS.en[emotionId] ?? emotionId;
}
