import type { Language } from '@/constants/i18n';
import type { TriggerCategoryId } from '@/constants/trigger-catalog';

const TRIGGER_CATEGORY_LABELS: Record<Language, Record<TriggerCategoryId, string>> = {
  ru: {
    'sleep-fatigue': 'Сон и усталость',
    stress: 'Стресс',
    health: 'Здоровье',
    'food-substances': 'Питание и вещества',
    medications: 'Лекарства',
    'physical-load': 'Физическая нагрузка',
    'public-places': 'Общественные места',
    'emotional-events': 'Эмоциональные события',
    sensory: 'Сенсорные факторы',
    hormonal: 'Гормональные факторы',
    internal: 'Внутренние триггеры',
  },
  en: {
    'sleep-fatigue': 'Sleep and fatigue',
    stress: 'Stress',
    health: 'Health',
    'food-substances': 'Food and substances',
    medications: 'Medications',
    'physical-load': 'Physical exertion',
    'public-places': 'Public places',
    'emotional-events': 'Emotional events',
    sensory: 'Sensory factors',
    hormonal: 'Hormonal factors',
    internal: 'Internal triggers',
  },
  es: {
    'sleep-fatigue': 'Sleep and fatigue',
    stress: 'Stress',
    health: 'Health',
    'food-substances': 'Food and substances',
    medications: 'Medications',
    'physical-load': 'Physical exertion',
    'public-places': 'Public places',
    'emotional-events': 'Emotional events',
    sensory: 'Sensory factors',
    hormonal: 'Hormonal factors',
    internal: 'Internal triggers',
  },
  fr: {
    'sleep-fatigue': 'Sleep and fatigue',
    stress: 'Stress',
    health: 'Health',
    'food-substances': 'Food and substances',
    medications: 'Medications',
    'physical-load': 'Physical exertion',
    'public-places': 'Public places',
    'emotional-events': 'Emotional events',
    sensory: 'Sensory factors',
    hormonal: 'Hormonal factors',
    internal: 'Internal triggers',
  },
  de: {
    'sleep-fatigue': 'Sleep and fatigue',
    stress: 'Stress',
    health: 'Health',
    'food-substances': 'Food and substances',
    medications: 'Medications',
    'physical-load': 'Physical exertion',
    'public-places': 'Public places',
    'emotional-events': 'Emotional events',
    sensory: 'Sensory factors',
    hormonal: 'Hormonal factors',
    internal: 'Internal triggers',
  },
  zh: {
    'sleep-fatigue': 'Sleep and fatigue',
    stress: 'Stress',
    health: 'Health',
    'food-substances': 'Food and substances',
    medications: 'Medications',
    'physical-load': 'Physical exertion',
    'public-places': 'Public places',
    'emotional-events': 'Emotional events',
    sensory: 'Sensory factors',
    hormonal: 'Hormonal factors',
    internal: 'Internal triggers',
  },
  pt: {
    'sleep-fatigue': 'Sleep and fatigue',
    stress: 'Stress',
    health: 'Health',
    'food-substances': 'Food and substances',
    medications: 'Medications',
    'physical-load': 'Physical exertion',
    'public-places': 'Public places',
    'emotional-events': 'Emotional events',
    sensory: 'Sensory factors',
    hormonal: 'Hormonal factors',
    internal: 'Internal triggers',
  },
  it: {
    'sleep-fatigue': 'Sleep and fatigue',
    stress: 'Stress',
    health: 'Health',
    'food-substances': 'Food and substances',
    medications: 'Medications',
    'physical-load': 'Physical exertion',
    'public-places': 'Public places',
    'emotional-events': 'Emotional events',
    sensory: 'Sensory factors',
    hormonal: 'Hormonal factors',
    internal: 'Internal triggers',
  },
};

const TRIGGER_LABELS_RU: Record<string, string> = {
  'lack-of-sleep': 'Недосып',
  'poor-sleep-quality': 'Плохое качество сна',
  nightmare: 'Ночной кошмар',
  overfatigue: 'Переутомление',
  'work-stress': 'Рабочий стресс',
  exams: 'Учеба / экзамены',
  'financial-worry': 'Финансовые переживания',
  conflict: 'Конфликт',
  'family-problems': 'Семейные проблемы',
  overload: 'Перегрузка делами',
  uncertainty: 'Неопределенность',
  'bad-news': 'Плохие новости',
  'cold-illness': 'Простуда / болезнь',
  fever: 'Повышенная температура',
  'dental-treatment': 'Лечение зубов',
  'doctor-visit': 'Посещение врача',
  'waiting-test-results': 'Ожидание результатов анализов',
  pain: 'Боль',
  'new-body-sensations': 'Новые телесные ощущения',
  coffee: 'Кофе',
  'energy-drink': 'Энергетик',
  'strong-tea': 'Крепкий чай',
  alcohol: 'Алкоголь',
  'smoking-nicotine': 'Курение / никотин',
  hunger: 'Голод',
  overeating: 'Переедание',
  dehydration: 'Недостаток воды',
  'missed-medication': 'Пропуск лекарства',
  'new-medication': 'Начало нового препарата',
  'dose-change': 'Изменение дозировки',
  'side-effects': 'Побочные эффекты',
  'intense-workout': 'Интенсивная тренировка',
  'long-walk': 'Длительная прогулка',
  overheating: 'Перегрев',
  'sauna-bath': 'Сауна / баня',
  crowd: 'Толпа',
  shop: 'Магазин',
  queue: 'Очередь',
  mall: 'Торговый центр',
  metro: 'Метро',
  bus: 'Автобус',
  airplane: 'Самолет',
  elevator: 'Лифт',
  bridge: 'Мост',
  'traffic-jam': 'Пробка в автомобиле',
  argument: 'Ссора',
  'public-speaking': 'Публичное выступление',
  'important-meeting': 'Важная встреча',
  'phone-call': 'Телефонный звонок',
  waiting: 'Ожидание',
  'joyful-event': 'Радостное событие',
  'strong-excitement': 'Сильное волнение',
  heat: 'Жара',
  stuffiness: 'Духота',
  'loud-noise': 'Громкий шум',
  'bright-light': 'Яркий свет',
  'strong-smell': 'Резкий запах',
  menstruation: 'Менструация',
  pms: 'ПМС',
  ovulation: 'Овуляция',
  pregnancy: 'Беременность',
  postpartum: 'Послеродовой период',
  'racing-heart': 'Учащенное сердцебиение',
  dizziness: 'Головокружение',
  'shortness-of-breath': 'Одышка',
  'stomach-discomfort': 'Дискомфорт в желудке',
  'chest-pain': 'Боль в груди',
  tingling: 'Покалывание',
  'muscle-tension': 'Мышечное напряжение',
};

const TRIGGER_LABELS_EN: Record<string, string> = {
  'lack-of-sleep': 'Lack of sleep',
  'poor-sleep-quality': 'Poor sleep quality',
  nightmare: 'Nightmare',
  overfatigue: 'Overfatigue',
  'work-stress': 'Work stress',
  exams: 'Studies / exams',
  'financial-worry': 'Financial worries',
  conflict: 'Conflict',
  'family-problems': 'Family problems',
  overload: 'Too many tasks',
  uncertainty: 'Uncertainty',
  'bad-news': 'Bad news',
  'cold-illness': 'Cold / illness',
  fever: 'Fever',
  'dental-treatment': 'Dental treatment',
  'doctor-visit': 'Doctor visit',
  'waiting-test-results': 'Waiting for test results',
  pain: 'Pain',
  'new-body-sensations': 'New body sensations',
  coffee: 'Coffee',
  'energy-drink': 'Energy drink',
  'strong-tea': 'Strong tea',
  alcohol: 'Alcohol',
  'smoking-nicotine': 'Smoking / nicotine',
  hunger: 'Hunger',
  overeating: 'Overeating',
  dehydration: 'Not enough water',
  'missed-medication': 'Missed medication',
  'new-medication': 'Starting a new medication',
  'dose-change': 'Dose change',
  'side-effects': 'Side effects',
  'intense-workout': 'Intense workout',
  'long-walk': 'Long walk',
  overheating: 'Overheating',
  'sauna-bath': 'Sauna / bath',
  crowd: 'Crowd',
  shop: 'Shop',
  queue: 'Queue',
  mall: 'Shopping mall',
  metro: 'Subway',
  bus: 'Bus',
  airplane: 'Airplane',
  elevator: 'Elevator',
  bridge: 'Bridge',
  'traffic-jam': 'Traffic jam',
  argument: 'Argument',
  'public-speaking': 'Public speaking',
  'important-meeting': 'Important meeting',
  'phone-call': 'Phone call',
  waiting: 'Waiting',
  'joyful-event': 'Joyful event',
  'strong-excitement': 'Strong excitement',
  heat: 'Heat',
  stuffiness: 'Stuffy air',
  'loud-noise': 'Loud noise',
  'bright-light': 'Bright light',
  'strong-smell': 'Strong smell',
  menstruation: 'Menstruation',
  pms: 'PMS',
  ovulation: 'Ovulation',
  pregnancy: 'Pregnancy',
  postpartum: 'Postpartum period',
  'racing-heart': 'Racing heartbeat',
  dizziness: 'Dizziness',
  'shortness-of-breath': 'Shortness of breath',
  'stomach-discomfort': 'Stomach discomfort',
  'chest-pain': 'Chest pain',
  tingling: 'Tingling',
  'muscle-tension': 'Muscle tension',
};

const TRIGGER_LABELS_BY_LANGUAGE: Partial<Record<Language, Record<string, string>>> = {
  ru: TRIGGER_LABELS_RU,
  en: TRIGGER_LABELS_EN,
};

export function getTriggerCategoryLabel(language: Language, categoryId: TriggerCategoryId): string {
  return TRIGGER_CATEGORY_LABELS[language][categoryId] ?? TRIGGER_CATEGORY_LABELS.en[categoryId];
}

export function getTriggerLabel(language: Language, triggerId: string): string {
  const labels = TRIGGER_LABELS_BY_LANGUAGE[language] ?? TRIGGER_LABELS_EN;
  return labels[triggerId] ?? TRIGGER_LABELS_EN[triggerId] ?? triggerId;
}
