import type { Language } from '@/constants/i18n';
import type { TriggerCategoryId } from '@/constants/trigger-catalog';

const TRIGGER_CATEGORY_LABELS: Record<Language, Record<TriggerCategoryId, string>> = {
  ru: {
    'sleep-fatigue': 'Сон и усталость',
    stress: 'Стресс',
    health: 'Здоровье',
    'food-substances': 'Питание и вещества',
    medications: 'Лекарства',
    'physical-load': 'Физическая нагрузка',
    'public-places': 'Общественные места',
    'emotional-events': 'Эмоциональные события',
    sensory: 'Сенсорные факторы',
    hormonal: 'Гормональные факторы',
    internal: 'Внутренние триггеры',
  },
  en: {
    'sleep-fatigue': 'Sleep and fatigue',
    stress: 'Stress',
    health: 'Health',
    'food-substances': 'Food and substances',
    medications: 'Medications',
    'physical-load': 'Physical exertion',
    'public-places': 'Public places',
    'emotional-events': 'Emotional events',
    sensory: 'Sensory factors',
    hormonal: 'Hormonal factors',
    internal: 'Internal triggers',
  },
  es: {
    'sleep-fatigue': 'Sueño y fatiga',
    stress: 'Estrés',
    health: 'Salud',
    'food-substances': 'Alimentación y sustancias',
    medications: 'Medicamentos',
    'physical-load': 'Esfuerzo físico',
    'public-places': 'Lugares públicos',
    'emotional-events': 'Eventos emocionales',
    sensory: 'Factores sensoriales',
    hormonal: 'Factores hormonales',
    internal: 'Desencadenantes internos',
  },
  fr: {
    'sleep-fatigue': 'Sommeil et fatigue',
    stress: 'Stress',
    health: 'Santé',
    'food-substances': 'Alimentation et substances',
    medications: 'Médicaments',
    'physical-load': 'Effort physique',
    'public-places': 'Lieux publics',
    'emotional-events': 'Événements émotionnels',
    sensory: 'Facteurs sensoriels',
    hormonal: 'Facteurs hormonaux',
    internal: 'Déclencheurs internes',
  },
  de: {
    'sleep-fatigue': 'Schlaf und Müdigkeit',
    stress: 'Stress',
    health: 'Gesundheit',
    'food-substances': 'Ernährung und Substanzen',
    medications: 'Medikamente',
    'physical-load': 'Körperliche Belastung',
    'public-places': 'Öffentliche Orte',
    'emotional-events': 'Emotionale Ereignisse',
    sensory: 'Sensorische Faktoren',
    hormonal: 'Hormonelle Faktoren',
    internal: 'Innere Auslöser',
  },
  zh: {
    'sleep-fatigue': '睡眠与疲劳',
    stress: '压力',
    health: '健康',
    'food-substances': '饮食与物质',
    medications: '药物',
    'physical-load': '体力活动',
    'public-places': '公共场所',
    'emotional-events': '情绪事件',
    sensory: '感官因素',
    hormonal: '激素因素',
    internal: '内在诱因',
  },
  pt: {
    'sleep-fatigue': 'Sono e fadiga',
    stress: 'Estresse',
    health: 'Saúde',
    'food-substances': 'Alimentação e substâncias',
    medications: 'Medicamentos',
    'physical-load': 'Esforço físico',
    'public-places': 'Locais públicos',
    'emotional-events': 'Eventos emocionais',
    sensory: 'Fatores sensoriais',
    hormonal: 'Fatores hormonais',
    internal: 'Gatilhos internos',
  },
  it: {
    'sleep-fatigue': 'Sonno e affaticamento',
    stress: 'Stress',
    health: 'Salute',
    'food-substances': 'Cibo e sostanze',
    medications: 'Farmaci',
    'physical-load': 'Sforzo fisico',
    'public-places': 'Luoghi pubblici',
    'emotional-events': 'Eventi emotivi',
    sensory: 'Fattori sensoriali',
    hormonal: 'Fattori ormonali',
    internal: 'Trigger interni',
  },
  ja: {
    'sleep-fatigue': '睡眠と疲労',
    stress: 'ストレス',
    health: '健康',
    'food-substances': '食事と物質',
    medications: '薬',
    'physical-load': '身体活動',
    'public-places': '公共の場',
    'emotional-events': '感情的な出来事',
    sensory: '感覚的要因',
    hormonal: 'ホルモン要因',
    internal: '内的トリガー',
  },
  ko: {
    'sleep-fatigue': '수면과 피로',
    stress: '스트레스',
    health: '건강',
    'food-substances': '음식과 물질',
    medications: '약물',
    'physical-load': '신체 활동',
    'public-places': '공공장소',
    'emotional-events': '감정적 사건',
    sensory: '감각 요인',
    hormonal: '호르몬 요인',
    internal: '내적 유발 요인',
  },
};

const TRIGGER_LABELS_RU: Record<string, string> = {
  'lack-of-sleep': 'Недосып',
  'poor-sleep-quality': 'Плохое качество сна',
  nightmare: 'Ночной кошмар',
  overfatigue: 'Переутомление',
  'work-stress': 'Рабочий стресс',
  exams: 'Учеба / экзамены',
  'financial-worry': 'Финансовые переживания',
  conflict: 'Конфликт',
  'family-problems': 'Семейные проблемы',
  overload: 'Перегрузка делами',
  uncertainty: 'Неопределенность',
  'bad-news': 'Плохие новости',
  'cold-illness': 'Простуда / болезнь',
  fever: 'Повышенная температура',
  'dental-treatment': 'Лечение зубов',
  'doctor-visit': 'Посещение врача',
  'waiting-test-results': 'Ожидание результатов анализов',
  pain: 'Боль',
  'new-body-sensations': 'Новые телесные ощущения',
  coffee: 'Кофе',
  'energy-drink': 'Энергетик',
  'strong-tea': 'Крепкий чай',
  alcohol: 'Алкоголь',
  'smoking-nicotine': 'Курение / никотин',
  hunger: 'Голод',
  overeating: 'Переедание',
  dehydration: 'Недостаток воды',
  'missed-medication': 'Пропуск лекарства',
  'new-medication': 'Начало нового препарата',
  'dose-change': 'Изменение дозировки',
  'side-effects': 'Побочные эффекты',
  'intense-workout': 'Интенсивная тренировка',
  'long-walk': 'Длительная прогулка',
  overheating: 'Перегрев',
  'sauna-bath': 'Сауна / баня',
  crowd: 'Толпа',
  shop: 'Магазин',
  queue: 'Очередь',
  mall: 'Торговый центр',
  metro: 'Метро',
  bus: 'Автобус',
  airplane: 'Самолет',
  elevator: 'Лифт',
  bridge: 'Мост',
  'traffic-jam': 'Пробка в автомобиле',
  argument: 'Ссора',
  'public-speaking': 'Публичное выступление',
  'important-meeting': 'Важная встреча',
  'phone-call': 'Телефонный звонок',
  waiting: 'Ожидание',
  'joyful-event': 'Радостное событие',
  'strong-excitement': 'Сильное волнение',
  heat: 'Жара',
  stuffiness: 'Духота',
  'loud-noise': 'Громкий шум',
  'bright-light': 'Яркий свет',
  'strong-smell': 'Резкий запах',
  menstruation: 'Менструация',
  pms: 'ПМС',
  ovulation: 'Овуляция',
  pregnancy: 'Беременность',
  postpartum: 'Послеродовой период',
  'racing-heart': 'Учащенное сердцебиение',
  dizziness: 'Головокружение',
  'shortness-of-breath': 'Одышка',
  'stomach-discomfort': 'Дискомфорт в желудке',
  'chest-pain': 'Боль в груди',
  tingling: 'Покалывание',
  'muscle-tension': 'Мышечное напряжение',
};

const TRIGGER_LABELS_EN: Record<string, string> = {
  'lack-of-sleep': 'Lack of sleep',
  'poor-sleep-quality': 'Poor sleep quality',
  nightmare: 'Nightmare',
  overfatigue: 'Overfatigue',
  'work-stress': 'Work stress',
  exams: 'Studies / exams',
  'financial-worry': 'Financial worries',
  conflict: 'Conflict',
  'family-problems': 'Family problems',
  overload: 'Too many tasks',
  uncertainty: 'Uncertainty',
  'bad-news': 'Bad news',
  'cold-illness': 'Cold / illness',
  fever: 'Fever',
  'dental-treatment': 'Dental treatment',
  'doctor-visit': 'Doctor visit',
  'waiting-test-results': 'Waiting for test results',
  pain: 'Pain',
  'new-body-sensations': 'New body sensations',
  coffee: 'Coffee',
  'energy-drink': 'Energy drink',
  'strong-tea': 'Strong tea',
  alcohol: 'Alcohol',
  'smoking-nicotine': 'Smoking / nicotine',
  hunger: 'Hunger',
  overeating: 'Overeating',
  dehydration: 'Not enough water',
  'missed-medication': 'Missed medication',
  'new-medication': 'Starting a new medication',
  'dose-change': 'Dose change',
  'side-effects': 'Side effects',
  'intense-workout': 'Intense workout',
  'long-walk': 'Long walk',
  overheating: 'Overheating',
  'sauna-bath': 'Sauna / bath',
  crowd: 'Crowd',
  shop: 'Shop',
  queue: 'Queue',
  mall: 'Shopping mall',
  metro: 'Subway',
  bus: 'Bus',
  airplane: 'Airplane',
  elevator: 'Elevator',
  bridge: 'Bridge',
  'traffic-jam': 'Traffic jam',
  argument: 'Argument',
  'public-speaking': 'Public speaking',
  'important-meeting': 'Important meeting',
  'phone-call': 'Phone call',
  waiting: 'Waiting',
  'joyful-event': 'Joyful event',
  'strong-excitement': 'Strong excitement',
  heat: 'Heat',
  stuffiness: 'Stuffy air',
  'loud-noise': 'Loud noise',
  'bright-light': 'Bright light',
  'strong-smell': 'Strong smell',
  menstruation: 'Menstruation',
  pms: 'PMS',
  ovulation: 'Ovulation',
  pregnancy: 'Pregnancy',
  postpartum: 'Postpartum period',
  'racing-heart': 'Racing heartbeat',
  dizziness: 'Dizziness',
  'shortness-of-breath': 'Shortness of breath',
  'stomach-discomfort': 'Stomach discomfort',
  'chest-pain': 'Chest pain',
  tingling: 'Tingling',
  'muscle-tension': 'Muscle tension',
};

const TRIGGER_LABELS_ES: Record<string, string> = {
  'lack-of-sleep': 'Falta de sueño',
  'poor-sleep-quality': 'Mala calidad del sueño',
  nightmare: 'Pesadilla',
  overfatigue: 'Agotamiento extremo',
  'work-stress': 'Estrés laboral',
  exams: 'Estudios / exámenes',
  'financial-worry': 'Preocupaciones económicas',
  conflict: 'Conflicto',
  'family-problems': 'Problemas familiares',
  overload: 'Sobrecarga de tareas',
  uncertainty: 'Incertidumbre',
  'bad-news': 'Malas noticias',
  'cold-illness': 'Resfriado / enfermedad',
  fever: 'Fiebre',
  'dental-treatment': 'Tratamiento dental',
  'doctor-visit': 'Visita al médico',
  'waiting-test-results': 'Espera de resultados de pruebas',
  pain: 'Dolor',
  'new-body-sensations': 'Nuevas sensaciones corporales',
  coffee: 'Café',
  'energy-drink': 'Bebida energética',
  'strong-tea': 'Té fuerte',
  alcohol: 'Alcohol',
  'smoking-nicotine': 'Tabaco / nicotina',
  hunger: 'Hambre',
  overeating: 'Comer en exceso',
  dehydration: 'Falta de agua',
  'missed-medication': 'Medicamento omitido',
  'new-medication': 'Inicio de un nuevo medicamento',
  'dose-change': 'Cambio de dosis',
  'side-effects': 'Efectos secundarios',
  'intense-workout': 'Entrenamiento intenso',
  'long-walk': 'Caminata prolongada',
  overheating: 'Sobrecalentamiento',
  'sauna-bath': 'Sauna / baño',
  crowd: 'Multitud',
  shop: 'Tienda',
  queue: 'Fila / cola',
  mall: 'Centro comercial',
  metro: 'Metro',
  bus: 'Autobús',
  airplane: 'Avión',
  elevator: 'Ascensor',
  bridge: 'Puente',
  'traffic-jam': 'Atasco de tráfico',
  argument: 'Discusión',
  'public-speaking': 'Hablar en público',
  'important-meeting': 'Reunión importante',
  'phone-call': 'Llamada telefónica',
  waiting: 'Espera',
  'joyful-event': 'Acontecimiento alegre',
  'strong-excitement': 'Fuerte emoción',
  heat: 'Calor',
  stuffiness: 'Aire cargado',
  'loud-noise': 'Ruido fuerte',
  'bright-light': 'Luz intensa',
  'strong-smell': 'Olor fuerte',
  menstruation: 'Menstruación',
  pms: 'Síndrome premenstrual',
  ovulation: 'Ovulación',
  pregnancy: 'Embarazo',
  postpartum: 'Período posparto',
  'racing-heart': 'Palpitaciones',
  dizziness: 'Mareo',
  'shortness-of-breath': 'Dificultad para respirar',
  'stomach-discomfort': 'Malestar estomacal',
  'chest-pain': 'Dolor en el pecho',
  tingling: 'Hormigueo',
  'muscle-tension': 'Tensión muscular',
};

const TRIGGER_LABELS_FR: Record<string, string> = {
  'lack-of-sleep': 'Manque de sommeil',
  'poor-sleep-quality': 'Mauvaise qualité de sommeil',
  nightmare: 'Cauchemar',
  overfatigue: 'Épuisement',
  'work-stress': 'Stress au travail',
  exams: 'Études / examens',
  'financial-worry': 'Soucis financiers',
  conflict: 'Conflit',
  'family-problems': 'Problèmes familiaux',
  overload: 'Surcharge de tâches',
  uncertainty: 'Incertitude',
  'bad-news': 'Mauvaises nouvelles',
  'cold-illness': 'Rhume / maladie',
  fever: 'Fièvre',
  'dental-treatment': 'Soins dentaires',
  'doctor-visit': 'Consultation médicale',
  'waiting-test-results': 'Attente des résultats d\'analyses',
  pain: 'Douleur',
  'new-body-sensations': 'Nouvelles sensations corporelles',
  coffee: 'Café',
  'energy-drink': 'Boisson énergisante',
  'strong-tea': 'Thé fort',
  alcohol: 'Alcool',
  'smoking-nicotine': 'Tabac / nicotine',
  hunger: 'Faim',
  overeating: 'Excès alimentaire',
  dehydration: 'Manque d\'eau',
  'missed-medication': 'Médicament oublié',
  'new-medication': 'Début d\'un nouveau traitement',
  'dose-change': 'Changement de posologie',
  'side-effects': 'Effets secondaires',
  'intense-workout': 'Entraînement intensif',
  'long-walk': 'Longue marche',
  overheating: 'Surchauffe',
  'sauna-bath': 'Sauna / bain',
  crowd: 'Foule',
  shop: 'Magasin',
  queue: 'File d\'attente',
  mall: 'Centre commercial',
  metro: 'Métro',
  bus: 'Bus',
  airplane: 'Avion',
  elevator: 'Ascenseur',
  bridge: 'Pont',
  'traffic-jam': 'Embouteillage',
  argument: 'Dispute',
  'public-speaking': 'Prise de parole en public',
  'important-meeting': 'Réunion importante',
  'phone-call': 'Appel téléphonique',
  waiting: 'Attente',
  'joyful-event': 'Événement joyeux',
  'strong-excitement': 'Forte excitation',
  heat: 'Chaleur',
  stuffiness: 'Air vicié',
  'loud-noise': 'Bruit fort',
  'bright-light': 'Lumière vive',
  'strong-smell': 'Odeur forte',
  menstruation: 'Menstruation',
  pms: 'SPM',
  ovulation: 'Ovulation',
  pregnancy: 'Grossesse',
  postpartum: 'Période post-partum',
  'racing-heart': 'Palpitations',
  dizziness: 'Vertiges',
  'shortness-of-breath': 'Essoufflement',
  'stomach-discomfort': 'Inconfort gastrique',
  'chest-pain': 'Douleur thoracique',
  tingling: 'Picotements',
  'muscle-tension': 'Tension musculaire',
};

const TRIGGER_LABELS_DE: Record<string, string> = {
  'lack-of-sleep': 'Schlafmangel',
  'poor-sleep-quality': 'Schlechte Schlafqualität',
  nightmare: 'Alptraum',
  overfatigue: 'Übermüdung',
  'work-stress': 'Arbeitsstress',
  exams: 'Studium / Prüfungen',
  'financial-worry': 'Finanzielle Sorgen',
  conflict: 'Konflikt',
  'family-problems': 'Familienprobleme',
  overload: 'Überlastung',
  uncertainty: 'Unsicherheit',
  'bad-news': 'Schlechte Nachrichten',
  'cold-illness': 'Erkältung / Krankheit',
  fever: 'Fieber',
  'dental-treatment': 'Zahnbehandlung',
  'doctor-visit': 'Arztbesuch',
  'waiting-test-results': 'Warten auf Testergebnisse',
  pain: 'Schmerz',
  'new-body-sensations': 'Neue Körperempfindungen',
  coffee: 'Kaffee',
  'energy-drink': 'Energydrink',
  'strong-tea': 'Starker Tee',
  alcohol: 'Alkohol',
  'smoking-nicotine': 'Rauchen / Nikotin',
  hunger: 'Hunger',
  overeating: 'Überessen',
  dehydration: 'Zu wenig Wasser',
  'missed-medication': 'Medikament vergessen',
  'new-medication': 'Beginn eines neuen Medikaments',
  'dose-change': 'Dosisänderung',
  'side-effects': 'Nebenwirkungen',
  'intense-workout': 'Intensives Training',
  'long-walk': 'Langer Spaziergang',
  overheating: 'Überhitzung',
  'sauna-bath': 'Sauna / Bad',
  crowd: 'Menschenmenge',
  shop: 'Geschäft',
  queue: 'Warteschlange',
  mall: 'Einkaufszentrum',
  metro: 'U-Bahn',
  bus: 'Bus',
  airplane: 'Flugzeug',
  elevator: 'Aufzug',
  bridge: 'Brücke',
  'traffic-jam': 'Stau',
  argument: 'Streit',
  'public-speaking': 'Öffentlicher Auftritt',
  'important-meeting': 'Wichtiges Meeting',
  'phone-call': 'Telefonanruf',
  waiting: 'Warten',
  'joyful-event': 'Freudiges Ereignis',
  'strong-excitement': 'Starke Aufregung',
  heat: 'Hitze',
  stuffiness: 'Stickige Luft',
  'loud-noise': 'Lärm',
  'bright-light': 'Helles Licht',
  'strong-smell': 'Starker Geruch',
  menstruation: 'Menstruation',
  pms: 'PMS',
  ovulation: 'Eisprung',
  pregnancy: 'Schwangerschaft',
  postpartum: 'Wochenbett',
  'racing-heart': 'Herzrasen',
  dizziness: 'Schwindel',
  'shortness-of-breath': 'Atemnot',
  'stomach-discomfort': 'Magenbeschwerden',
  'chest-pain': 'Brustschmerzen',
  tingling: 'Kribbeln',
  'muscle-tension': 'Muskelverspannung',
};

const TRIGGER_LABELS_ZH: Record<string, string> = {
  'lack-of-sleep': '睡眠不足',
  'poor-sleep-quality': '睡眠质量差',
  nightmare: '噩梦',
  overfatigue: '过度疲劳',
  'work-stress': '工作压力',
  exams: '学业 / 考试',
  'financial-worry': '财务担忧',
  conflict: '冲突',
  'family-problems': '家庭问题',
  overload: '任务过多',
  uncertainty: '不确定性',
  'bad-news': '坏消息',
  'cold-illness': '感冒 / 疾病',
  fever: '发烧',
  'dental-treatment': '牙科治疗',
  'doctor-visit': '就医',
  'waiting-test-results': '等待检查结果',
  pain: '疼痛',
  'new-body-sensations': '新的身体感受',
  coffee: '咖啡',
  'energy-drink': '能量饮料',
  'strong-tea': '浓茶',
  alcohol: '酒精',
  'smoking-nicotine': '吸烟 / 尼古丁',
  hunger: '饥饿',
  overeating: '暴饮暴食',
  dehydration: '缺水',
  'missed-medication': '漏服药物',
  'new-medication': '开始新药物',
  'dose-change': '剂量变更',
  'side-effects': '副作用',
  'intense-workout': '高强度锻炼',
  'long-walk': '长时间步行',
  overheating: '过热',
  'sauna-bath': '桑拿 / 泡澡',
  crowd: '人群',
  shop: '商店',
  queue: '排队',
  mall: '商场',
  metro: '地铁',
  bus: '公交车',
  airplane: '飞机',
  elevator: '电梯',
  bridge: '桥梁',
  'traffic-jam': '交通堵塞',
  argument: '争吵',
  'public-speaking': '公开演讲',
  'important-meeting': '重要会议',
  'phone-call': '电话',
  waiting: '等待',
  'joyful-event': '开心的事件',
  'strong-excitement': '强烈兴奋',
  heat: '高温',
  stuffiness: '闷热',
  'loud-noise': '噪音',
  'bright-light': '强光',
  'strong-smell': '强烈气味',
  menstruation: '月经',
  pms: '经前综合征',
  ovulation: '排卵',
  pregnancy: '怀孕',
  postpartum: '产后',
  'racing-heart': '心跳加速',
  dizziness: '头晕',
  'shortness-of-breath': '呼吸困难',
  'stomach-discomfort': '胃部不适',
  'chest-pain': '胸痛',
  tingling: '发麻',
  'muscle-tension': '肌肉紧张',
};

const TRIGGER_LABELS_PT: Record<string, string> = {
  'lack-of-sleep': 'Falta de sono',
  'poor-sleep-quality': 'Má qualidade do sono',
  nightmare: 'Pesadelo',
  overfatigue: 'Exaustão',
  'work-stress': 'Estresse no trabalho',
  exams: 'Estudos / provas',
  'financial-worry': 'Preocupações financeiras',
  conflict: 'Conflito',
  'family-problems': 'Problemas familiares',
  overload: 'Excesso de tarefas',
  uncertainty: 'Incerteza',
  'bad-news': 'Más notícias',
  'cold-illness': 'Resfriado / doença',
  fever: 'Febre',
  'dental-treatment': 'Tratamento dentário',
  'doctor-visit': 'Consulta médica',
  'waiting-test-results': 'Espera por resultados de exames',
  pain: 'Dor',
  'new-body-sensations': 'Novas sensações corporais',
  coffee: 'Café',
  'energy-drink': 'Bebida energética',
  'strong-tea': 'Chá forte',
  alcohol: 'Álcool',
  'smoking-nicotine': 'Tabagismo / nicotina',
  hunger: 'Fome',
  overeating: 'Comer em excesso',
  dehydration: 'Falta de água',
  'missed-medication': 'Medicação esquecida',
  'new-medication': 'Início de um novo medicamento',
  'dose-change': 'Alteração de dose',
  'side-effects': 'Efeitos colaterais',
  'intense-workout': 'Treino intenso',
  'long-walk': 'Caminhada longa',
  overheating: 'Superaquecimento',
  'sauna-bath': 'Sauna / banho',
  crowd: 'Multidão',
  shop: 'Loja',
  queue: 'Fila',
  mall: 'Shopping',
  metro: 'Metrô',
  bus: 'Ônibus',
  airplane: 'Avião',
  elevator: 'Elevador',
  bridge: 'Ponte',
  'traffic-jam': 'Engarrafamento',
  argument: 'Discussão',
  'public-speaking': 'Falar em público',
  'important-meeting': 'Reunião importante',
  'phone-call': 'Ligação telefônica',
  waiting: 'Espera',
  'joyful-event': 'Evento alegre',
  'strong-excitement': 'Forte emoção',
  heat: 'Calor',
  stuffiness: 'Ar abafado',
  'loud-noise': 'Barulho alto',
  'bright-light': 'Luz forte',
  'strong-smell': 'Cheiro forte',
  menstruation: 'Menstruação',
  pms: 'TPM',
  ovulation: 'Ovulação',
  pregnancy: 'Gravidez',
  postpartum: 'Período pós-parto',
  'racing-heart': 'Coração acelerado',
  dizziness: 'Tontura',
  'shortness-of-breath': 'Falta de ar',
  'stomach-discomfort': 'Desconforto estomacal',
  'chest-pain': 'Dor no peito',
  tingling: 'Formigamento',
  'muscle-tension': 'Tensão muscular',
};

const TRIGGER_LABELS_IT: Record<string, string> = {
  'lack-of-sleep': 'Mancanza di sonno',
  'poor-sleep-quality': 'Scarsa qualità del sonno',
  nightmare: 'Incubo',
  overfatigue: 'Eccessiva stanchezza',
  'work-stress': 'Stress lavorativo',
  exams: 'Studio / esami',
  'financial-worry': 'Preoccupazioni finanziarie',
  conflict: 'Conflitto',
  'family-problems': 'Problemi familiari',
  overload: 'Troppi compiti',
  uncertainty: 'Incertezza',
  'bad-news': 'Cattive notizie',
  'cold-illness': 'Raffreddore / malattia',
  fever: 'Febbre',
  'dental-treatment': 'Cura dentale',
  'doctor-visit': 'Visita medica',
  'waiting-test-results': 'Attesa risultati degli esami',
  pain: 'Dolore',
  'new-body-sensations': 'Nuove sensazioni corporee',
  coffee: 'Caffè',
  'energy-drink': 'Bevanda energetica',
  'strong-tea': 'Tè forte',
  alcohol: 'Alcol',
  'smoking-nicotine': 'Fumo / nicotina',
  hunger: 'Fame',
  overeating: 'Abbuffata',
  dehydration: 'Poca acqua',
  'missed-medication': 'Farmaco saltato',
  'new-medication': 'Inizio di un nuovo farmaco',
  'dose-change': 'Cambio di dose',
  'side-effects': 'Effetti collaterali',
  'intense-workout': 'Allenamento intenso',
  'long-walk': 'Passeggiata lunga',
  overheating: 'Surriscaldamento',
  'sauna-bath': 'Sauna / bagno',
  crowd: 'Folla',
  shop: 'Negozio',
  queue: 'Coda',
  mall: 'Centro commerciale',
  metro: 'Metropolitana',
  bus: 'Autobus',
  airplane: 'Aereo',
  elevator: 'Ascensore',
  bridge: 'Ponte',
  'traffic-jam': 'Ingorgo',
  argument: 'Litigio',
  'public-speaking': 'Parlare in pubblico',
  'important-meeting': 'Riunione importante',
  'phone-call': 'Telefonata',
  waiting: 'Attesa',
  'joyful-event': 'Evento gioioso',
  'strong-excitement': 'Forte emozione',
  heat: 'Caldo',
  stuffiness: 'Aria pesante',
  'loud-noise': 'Rumore forte',
  'bright-light': 'Luce intensa',
  'strong-smell': 'Odore forte',
  menstruation: 'Mestruazione',
  pms: 'Sindrome premestruale',
  ovulation: 'Ovulazione',
  pregnancy: 'Gravidanza',
  postpartum: 'Periodo post-partum',
  'racing-heart': 'Battito accelerato',
  dizziness: 'Capogiro',
  'shortness-of-breath': 'Fiato corto',
  'stomach-discomfort': 'Disagio gastrico',
  'chest-pain': 'Dolore al petto',
  tingling: 'Formicolio',
  'muscle-tension': 'Tensione muscolare',
};

const TRIGGER_LABELS_JA: Record<string, string> = {
  'lack-of-sleep': '睡眠不足',
  'poor-sleep-quality': '睡眠の質が悪い',
  nightmare: '悪夢',
  overfatigue: '過度の疲労',
  'work-stress': '仕事のストレス',
  exams: '学業 / 試験',
  'financial-worry': '金銭的な心配',
  conflict: '対立',
  'family-problems': '家庭の問題',
  overload: 'タスク過多',
  uncertainty: '不確実性',
  'bad-news': '悪いニュース',
  'cold-illness': '風邪 / 病気',
  fever: '発熱',
  'dental-treatment': '歯科治療',
  'doctor-visit': '通院',
  'waiting-test-results': '検査結果の待ち',
  pain: '痛み',
  'new-body-sensations': '新しい身体感覚',
  coffee: 'コーヒー',
  'energy-drink': 'エナジードリンク',
  'strong-tea': '濃いお茶',
  alcohol: 'アルコール',
  'smoking-nicotine': '喫煙 / ニコチン',
  hunger: '空腹',
  overeating: '食べ過ぎ',
  dehydration: '水分不足',
  'missed-medication': '服薬忘れ',
  'new-medication': '新しい薬の開始',
  'dose-change': '用量変更',
  'side-effects': '副作用',
  'intense-workout': '激しい運動',
  'long-walk': '長時間の散歩',
  overheating: '暑さによる不調',
  'sauna-bath': 'サウナ / 入浴',
  crowd: '人混み',
  shop: '店',
  queue: '行列',
  mall: 'ショッピングモール',
  metro: '地下鉄',
  bus: 'バス',
  airplane: '飛行機',
  elevator: 'エレベーター',
  bridge: '橋',
  'traffic-jam': '交通渋滞',
  argument: '口論',
  'public-speaking': '人前での発表',
  'important-meeting': '重要な会議',
  'phone-call': '電話',
  waiting: '待ち時間',
  'joyful-event': 'うれしい出来事',
  'strong-excitement': '強い興奮',
  heat: '暑さ',
  stuffiness: 'むっとした空気',
  'loud-noise': '大きな音',
  'bright-light': 'まぶしい光',
  'strong-smell': '強い匂い',
  menstruation: '月経',
  pms: 'PMS',
  ovulation: '排卵',
  pregnancy: '妊娠',
  postpartum: '産後',
  'racing-heart': '動悸',
  dizziness: 'めまい',
  'shortness-of-breath': '息切れ',
  'stomach-discomfort': '胃の不快感',
  'chest-pain': '胸の痛み',
  tingling: 'しびれ',
  'muscle-tension': '筋肉の緊張',
};

const TRIGGER_LABELS_KO: Record<string, string> = {
  'lack-of-sleep': '수면 부족',
  'poor-sleep-quality': '수면의 질 저하',
  nightmare: '악몽',
  overfatigue: '과로',
  'work-stress': '직장 스트레스',
  exams: '학업 / 시험',
  'financial-worry': '재정적 걱정',
  conflict: '갈등',
  'family-problems': '가족 문제',
  overload: '과도한 업무',
  uncertainty: '불확실성',
  'bad-news': '나쁜 소식',
  'cold-illness': '감기 / 질병',
  fever: '발열',
  'dental-treatment': '치과 치료',
  'doctor-visit': '병원 방문',
  'waiting-test-results': '검사 결과 대기',
  pain: '통증',
  'new-body-sensations': '새로운 신체 감각',
  coffee: '커피',
  'energy-drink': '에너지 드링크',
  'strong-tea': '진한 차',
  alcohol: '알코올',
  'smoking-nicotine': '흡연 / 니코틴',
  hunger: '배고픔',
  overeating: '과식',
  dehydration: '수분 부족',
  'missed-medication': '약 복용 누락',
  'new-medication': '새 약 시작',
  'dose-change': '용량 변경',
  'side-effects': '부작용',
  'intense-workout': '격렬한 운동',
  'long-walk': '오래 걷기',
  overheating: '과열',
  'sauna-bath': '사우나 / 목욕',
  crowd: '군중',
  shop: '가게',
  queue: '줄 서기',
  mall: '쇼핑몰',
  metro: '지하철',
  bus: '버스',
  airplane: '비행기',
  elevator: '엘리베이터',
  bridge: '다리',
  'traffic-jam': '교통 체증',
  argument: '다툼',
  'public-speaking': '대중 앞 발표',
  'important-meeting': '중요한 회의',
  'phone-call': '전화',
  waiting: '대기',
  'joyful-event': '기쁜 일',
  'strong-excitement': '강한 흥분',
  heat: '더위',
  stuffiness: '답답함',
  'loud-noise': '큰 소음',
  'bright-light': '밝은 빛',
  'strong-smell': '강한 냄새',
  menstruation: '월경',
  pms: 'PMS',
  ovulation: '배란',
  pregnancy: '임신',
  postpartum: '산후',
  'racing-heart': '심박 증가',
  dizziness: '어지러움',
  'shortness-of-breath': '숨 가쁨',
  'stomach-discomfort': '위 불편',
  'chest-pain': '가슴 통증',
  tingling: '저림',
  'muscle-tension': '근육 긴장',
};

const TRIGGER_LABELS_BY_LANGUAGE: Record<Language, Record<string, string>> = {
  ru: TRIGGER_LABELS_RU,
  en: TRIGGER_LABELS_EN,
  es: TRIGGER_LABELS_ES,
  fr: TRIGGER_LABELS_FR,
  de: TRIGGER_LABELS_DE,
  zh: TRIGGER_LABELS_ZH,
  pt: TRIGGER_LABELS_PT,
  it: TRIGGER_LABELS_IT,
  ja: TRIGGER_LABELS_JA,
  ko: TRIGGER_LABELS_KO,
};

export function getTriggerCategoryLabel(language: Language, categoryId: TriggerCategoryId): string {
  return TRIGGER_CATEGORY_LABELS[language][categoryId] ?? TRIGGER_CATEGORY_LABELS.en[categoryId];
}

export function getTriggerLabel(language: Language, triggerId: string): string {
  const labels = TRIGGER_LABELS_BY_LANGUAGE[language] ?? TRIGGER_LABELS_EN;
  return labels[triggerId] ?? TRIGGER_LABELS_EN[triggerId] ?? triggerId;
}
